const mongoose = require('mongoose');

const auditLogSchema = new mongoose.Schema({
  entity: { type: String, required: true },
  entityId: { type: mongoose.Schema.Types.ObjectId, required: true },
  action: {
    type: String,
    enum: [
      'CREATE',
      'UPDATE',
      'REPLENISH',
      'APPROVE',
      'CANCEL',
      'MARK_INCIDENT',
      'CLOSE',
      'START_SHIFT',
      'END_SHIFT',
      'ADMIN_EDIT_SHIFT',
      'ADMIN_CLOSE_SHIFT',
      'CLOSING_SUBMITTED',
      'CLOSING_REOPENED',
      'CLOSING_FINALIZED',
      'UPDATE_DEFAULT_SHIFT',
      'CREATE_SCHEDULE_EXCEPTION',
      'UPDATE_SCHEDULE_EXCEPTION',
      'DELETE_SCHEDULE_EXCEPTION',
      'ACTIVATE',
      'DEACTIVATE',
      'DELETE',
      'DELETE_BLOCKED',
      'DRIVER_CREATE',
      'DRIVER_UPDATE',
      'DRIVER_ACTIVATE',
      'DRIVER_DEACTIVATE',
      'DRIVER_DELETE',
      'DRIVER_DELETE_BLOCKED',
      'MESSAGE_SENT',
      'MESSAGE_READ',
      'DISPATCH_CREATED',
      'DISPATCH_ACCEPTED',
      'DISPATCH_COMPLETED',
      'DISPATCH_CANCELLED',
      'REPLENISHMENT_REQUEST_CREATED',
      'REPLENISHMENT_REQUEST_UPDATED',
      'REPLENISHMENT_REQUEST_SENT',
      'REPLENISHMENT_REQUEST_FULFILLED',
      'REPLENISHMENT_REQUEST_CANCELLED',
    ],
    required: true,
  },
  changes: [
    {
      field: String,
      oldValue: mongoose.Schema.Types.Mixed,
      newValue: mongoose.Schema.Types.Mixed,
      _id: false,
    },
  ],
  performedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  performedAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model('AuditLog', auditLogSchema);
