const ROLES = {
  DRIVER: 'driver',
  MANAGER: 'manager',
  ADMIN: 'admin',
};

const PAYMENT_METHODS = ['cash', 'transfer'];

const SALE_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  CANCELLED: 'CANCELLED',
  INCIDENT: 'INCIDENT',
};

// Statuses that represent a real physical movement of stock out of the vehicle.
const INVENTORY_AFFECTING_SALE_STATUSES = [
  SALE_STATUSES.PENDING,
  SALE_STATUSES.APPROVED,
  SALE_STATUSES.INCIDENT,
];

const SESSION_STATUSES = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
};

const INVENTORY_COUNT_TYPES = {
  INITIAL: 'INITIAL',
  PARTIAL: 'PARTIAL',
  CLOSING: 'CLOSING',
  WEEKLY: 'WEEKLY',
};

const CLOSING_STATUSES = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
};

module.exports = {
  ROLES,
  PAYMENT_METHODS,
  SALE_STATUSES,
  INVENTORY_AFFECTING_SALE_STATUSES,
  SESSION_STATUSES,
  INVENTORY_COUNT_TYPES,
  CLOSING_STATUSES,
};
